Rails/Rails_Views/ninety-nine-cats-form-helpers/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #resources :cats, only: [:index, :show, :new, :create, :edit, :update]

  #routes for cats controller. collection/nested routes to cat_rental_requests controller.
  resources :cats do 
    resources :cat_rental_requests, only: [:index, :new, :create]
  end 

  #member routes for cat_rental_requests controller
  resources :cat_rental_requests do 
    get 'approve', on: :member
    get 'deny', on: :member
  end 

  # Defines the root path route ("/")
  root "cats#index"
end

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null

require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    CAT_COLORS = ["black", "grey", "mix", "orange", "white"]
        
    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, :inclusion => { :in => CAT_COLORS, :message => "%{value} is not a valid color. Choose 'black', 'grey', 'mix', 'orange', or 'white'." }
    validates :sex, :inclusion => { :in => %w(M F), :message => "%{value} is not a valid sex. Choose 'M' or 'F'." }
    validate :birth_date_cannot_be_future

    def self.get_cat_colors
        CAT_COLORS
    end

    def self.get_cat_ids_and_names 
        arr_of_ids_and_names = []
        Cat.all.each { |cat| arr_of_ids_and_names << ["#{cat.id} - #{cat.name}", cat.id] }  
        arr_of_ids_and_names
    end 

    def age 
        raise future_birth_date_error if birth_date_in_future?
        
        return age_in_days if cat_born_this_year_this_month? 

        years_old, months_old = get_initial_years_old_and_months_old_values
        years_old, months_old = adjust_years_old_and_months_old_values(years_old, months_old)
        years_old_word, months_old_word = get_years_old_word_and_months_old_word(years_old, months_old)

        compose_age_string(years_old, months_old, years_old_word, months_old_word)
    end 

    has_many :rental_requests, 
        primary_key: :id, 
        foreign_key: :cat_id, #cat_rental_requests table
        class_name: :CatRentalRequest, 
        dependent: :destroy

    has_one_attached :image, 
        dependent: :destroy

    private 

    def birth_date_cannot_be_future 
        errors.add(:birth_date, "can't be in future.") if birth_date.nil? || birth_date > Date.current
    end 

    def birth_date_in_future? 
        birth_date.year > Date.current.year || (birth_date.year == Date.current.year && birth_date.month > Date.current.month) || (birth_date.year == Date.current.year && birth_date.month == Date.current.month && birth_date.day > Date.current.day)  
    end 

    def future_birth_date_error
        "A cat can't have a birth date in the future. Please set the birth date to a date in the past."
    end 

    def cat_born_this_year_this_month? 
        Date.current.year == birth_date.year && Date.current.month == birth_date.month 
    end 

    def age_in_days 
        days_old = Date.current.day - birth_date.day
        if days_old == 1 
            "1 day old"
        else 
            "#{days_old} days old"
        end
    end 

    def get_initial_years_old_and_months_old_values
        years_old = Date.current.year - birth_date.year 
        months_old = Date.current.month - birth_date.month 
        [years_old, months_old]
    end 

    def adjust_years_old_and_months_old_values(years_old, months_old)
        if months_old < 0 
            months_old += 12 
            years_old -= 1 
        end 
        [years_old, months_old]
    end 

    def get_years_old_word_and_months_old_word(years_old, months_old)
        if months_old == 1 
            months_old_word = "month"
        else
            months_old_word = "months"
        end 

        if years_old == 1 
            years_old_word = "year"
        else 
            years_old_word = "years"
        end 

        [years_old_word, months_old_word]
    end 

    def compose_age_string(years_old, months_old, years_old_word, months_old_word)
        age_string = ""
        age_string += "#{years_old} #{years_old_word} " if years_old > 0 
        age_string += "#{months_old} #{months_old_word} " if months_old > 0 
        age_string += "old"
        age_string
    end 
end 

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index 
        @cats = Cat.all 
        render :index 
    end 

    def show 
        @cat = Cat.find_by(id: params[:id])
        @cat_rental_requests = CatRentalRequest.where(cat_id: @cat.id).order('start_date ASC')

        if @cat  
            render :show 
        else   
            redirect_to cats_url 
        end 
    end 

    def new 
        @cat = Cat.new
        render :new 
    end 

    def create 
        @cat = Cat.new(cat_params)

        if @cat.save
            redirect_to cat_url(@cat)
        else 
            render :new 
        end 
    end 

    def edit 
        @cat = Cat.find_by(id: params[:id])

        if @cat 
            render :edit 
        else   
            render :new 
        end 
    end 

    def update 
        @cat = Cat.find_by(id: params[:id])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else  
            render :edit 
        end   
    end 

    private 

    def cat_params 
        params.require(:cat).permit(:name, :color, :birth_date, :sex, :description, :image)
    end 
end 

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/views/cats/_cat.html.erb
<li>
    <% if cat.image.attached? %>
        <%= image_tag cat.image, style: "width: 100px; display: block" %> 
    <% end %>

    <a href="http://localhost:3000/cats/<%= cat.id %>"><%= cat.name %></a> 

    <% unless last_cat_id == cat.id %>
        <br><br>    
    <% end %>
</li>

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/views/cats/_form.html.erb
<% if cat && cat.persisted? %>
    <% if cat.image.attached? %>
        <%= image_tag cat.image, style: "width: 120px; display: block" %> 
    <% end %>
    <br>
<% end %>

<%= form_with model: cat do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :photo %>
        <%= f.file_field :image %>
    </div>
        <%= f.label :sex %>
        <%= f.label :sex, 'M' %>
        <%= f.radio_button :sex, 'M' %>
        <%= f.label :sex, 'F' %>
        <%= f.radio_button :sex, 'F' %>
    <div>
        <%= f.label :color %>
        <%= f.select :color, Cat.get_cat_colors, { prompt: "Select Color" } %>
    </div>
        <%= f.label :birth_date %>
        <%= f.date_field :birth_date %>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/views/cats/edit.html.erb
<h1>Edit a cat!</h1>

<%= render 'form', cat: @cat %>

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/views/cats/index.html.erb
<h1>All the Cats!</h1>

<ul>
    <%= render @cats, last_cat_id: @cats.last.id %>
</ul>

<!-- Button to Add a Cat -->
<%= button_to 'Add Cat', new_cat_url, method: :get %>

<br>

<!-- Button to Create a New Cat Rental Request -->
<%= button_to 'Add Cat Rental Request', new_cat_rental_request_url, method: :get %>

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/views/cats/new.html.erb
<h1>Add a cat!</h1>

<%= render 'form', cat: @cat %>

Rails/Rails_Views/ninety-nine-cats-form-helpers/app/views/cats/show.html.erb
<!-- Cat Photo -->
<% if @cat.image.attached? %>
    <%= image_tag @cat.image, style: "width: 150px; display: block" %> 
<% end %>

<!-- Cat Data -->
<table>
    <tbody>
        <tr>
            <td><b>Cat:</b></td>
            <td><b><%= @cat.name %></b></td>
        </tr>
        <tr>
            <td>Color:</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex:</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Birth Date:</td>
            <td><%= @cat.birth_date.to_formatted_s(:long) %></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><%= @cat.description %></td>
        </tr>
        <tr></tr><tr></tr><tr></tr>
        <tr>
            <td><%= button_to "Edit #{@cat.name}", edit_cat_url(@cat), method: :get %></td>
            <td><%= button_to "Create Rental Request for #{@cat.name}", new_cat_cat_rental_request_url(@cat), method: :get %></td>
        </tr>
    </tbody>
</table>

<br><br>

<!-- Cat Rental Request Data -->
<table>
    <% if @cat_rental_requests.exists? %>
        <thead>
            <tr>
                <th align="left">Rental Requests</th>
            </tr>
        </thead>
        <tbody>
            <% @cat_rental_requests.each do |request| %>
                <tr>
                    <td>Start Date:</td>
                    <td><%= request.start_date %></td>
                </tr>
                <tr>
                    <td>End Date:</td>
                    <td><%= request.end_date %></td>
                </tr>
                <tr>
                    <td>Status:</td>
                    <td><%= request.status %></td>
                </tr>
                <tr>
                    <% if request.pending? %>
                        <td><%= button_to 'Approve', approve_cat_rental_request_url(request.id), method: :get %></td> 
                        <td><%= button_to 'Deny', deny_cat_rental_request_url(request.id), method: :get %></td> 
                    <% end %>
                </tr>
                <tr></tr><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr>
            <% end %>    
        </tbody>
    <% else %>
        <thead>
            <tr>
                <th align="left"><%= @cat.name %> has no rental requests.</th>
            </tr>
        </thead>
    <% end %>
</table>